create table SOLVERS (SID TINYINT(11) NOT NULL AUTO_INCREMENT, NAME VARCHAR(256) NOT NULL, PRIMARY KEY(SID, NAME));
insert into SOLVERS (NAME) values ('CHOCO'),('JACOP'),('GECODE');

create table BENCHMARKS (BID TINYINT(11) NOT NULL AUTO_INCREMENT, NAME VARCHAR(32) NOT NULL, DATE DATE NOT NULL,
SID TINYINT(11) NOT NULL, PRIMARY KEY(BID,NAME,SID),FOREIGN KEY(SID) references SOLVERS(SID));

create table PROBLEMS (PID TINYINT(11) NOT NULL  AUTO_INCREMENT,NAME VARCHAR(256) NOT NULL,
RESOLUTION ENUM('SAT','MIN','MAX') NOT NULL, SOLUTION BIGINT(20) NULL, OPTIMAL TINYINT(1) NOT NULL,
PRIMARY KEY(PID, NAME));

create table RESOLUTIONS (BID TINYINT(11) NOT NULL, PID TINYINT(11) NOT NULL, BUILDING_TIME BIGINT(20) NOT NULL,
SOLVING_TIME BIGINT(20) NOT NULL, SOLUTION BIGINT(20) NULL, NB_SOL BIGINT(20) NOT NULL, NB_NODES BIGINT(20) NOT NULL,
NB_FAILS BIGINT(20) NOT NULL,
FOREIGN KEY(BID) references BENCHMAKS(BID), FOREIGN KEY (PID) references PROBLEMS(PID), PRIMARY KEY (BID, PID));
