#!/bin/sh

STOP_AT_FIRST="yes"
FREE_SEARCH="no"
NB_NODES=1
CHOCO_PATH=/Users/cprudhom/Sources/Galak/parser/src/fzn/
TIME_LIMIT=900000

usage="\
Usage: fzn_choco [<options>] [<file>]

    Parse and solve <file> using Choco.

OPTIONS:

    -h, --help
        Display this message.

    -a
        This causes the solver to search for, and output all solutions.
        When this option is not given the solver should search for, and output the first solution.

    -f
        When invoked with this option the solver ignores any specified search strategy.

    -p
        NOT YET AVAILABLE
        When invoked with this option the solver is free to use multiple threads and/or cores during search.
        The argument n specifies the number of cores that are available.  (The default is $NB_NODES.)

    -c, --choco-path
        Specify the path to choco JAR file and configuration file.

    --time-limit <n>
        Limit the resolution time of each problem instance to n seconds.  (The default is $TIME_LIMIT.)
"

while test $# -gt 0
do

    case "$1" in

        -h|--help)
            echo "$usage"
            exit 0
        ;;

        -a)
            STOP_AT_FIRST="no"
        ;;

        -f)
            FREE_SEARCH="yes"
        ;;

        -p)
            NB_NODES="$2"
            shift
        ;;

        -c|--choco-path)
            CHOCO_PATH="$2"
            shift
        ;;

        --time-limit)
            TIME_LIMIT="$2"
            shift
        ;;

        -*)
            echo "$0: unknown option \`$1'" 1>&2
            echo "$usage" 1>&2
            exit 2
        ;;

        *)
            break
        ;;

    esac
    shift
done

FILE=$*

CHOCO_JAR=$CHOCO_PATH/choco.jar
LOG_FILE=$CHOCO_PATH/config.xml

if test $# -eq 0
then
    echo "No flatzinc file found"
    exit 1
else
    ARGS="$FILE -tl $TIME_LIMIT -p $NB_NODES"
fi

if test "$STOP_AT_FIRST" = "no"
then
    echo "STOP_AT_FIRST"
    ARGS=$ARGS" -a"
fi

if test "$FREE_SEARCH" = "yes"
then
    echo "FREE_SEARCH"
    ARGS=$ARGS" -i"
fi

java -Xss64m -Xms64m -Xmx2048m -cp .:$CHOCO_JAR -Dlogback.configurationFile=$LOG_FILE parser.flatzinc.ParseAndSolve $ARGS