#!/bin/sh
OPTIONS="-en V"

IN=$1

clear
CP="."
CP="../../solver/target/solver-1.0-SNAPSHOT.jar:$CP"
CP="../../parser/target/parser-1.0-SNAPSHOT.jar:$CP"
CP="/Users/cprudhom/.m2/repository/args4j/args4j/2.0.12/args4j-2.0.12.jar:$CP"
CP="/Users/cprudhom/.m2/repository/jparsec/jparsec/2.0.1/jparsec-2.0.1.jar:$CP"
CP="/Users/cprudhom/.m2/repository/cglib/cglib-nodep/2.2/cglib-nodep-2.2.jar:$CP"
CP="/Users/cprudhom/.m2/repository/ch/qos/logback/logback-classic/0.9.24/logback-classic-0.9.24.jar:$CP"
CP="/Users/cprudhom/.m2/repository/ch/qos/logback/logback-core/0.9.24/logback-core-0.9.24.jar:$CP"
CP="/Users/cprudhom/.m2/repository/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar:$CP"
CP="/Users/cprudhom/.m2/repository/gnu/trove/2.1.0/trove-2.1.0.jar:$CP"
echo $CP

CMD="java -ea -cp $CP parser.flatzinc.ParseAndSolve ${OPTIONS}"
LIST=`find $IN -name "*.fzn"`
for fzn in $LIST
do
	CMD="$CMD -f $fzn"
	filen=`basename $fzn`
	fznnoext=`echo $filen |cut -d'.' -f1`
	fznsol="${fzn}.sol"
	echo "Processing ${fznnoext}"
	echo "${fznsol}"
	$CMD > ${fznsol}
	echo "Done!"
	echo "Check ${fznsol}"
done