#!/bin/sh

IN=$1
if [ -z $2 ]
then
	OUT="/Users/cprudhom/Documents/Projects/Documents/FlatZinc/"
else
	OUT=$2
fi

clear

LIST=`find $IN -name "*.mzn"`
for mzn in $LIST
do
	dirn=`dirname $mzn`
	filen=`basename $mzn`
	DATA=`find $dirn -name "*.dzn"`
	c=0
	mznnoext=`echo $filen |cut -d'.' -f1`
	mkdir $OUT/${mznnoext}
	echo "Processing ${mznnoext}\c"
	for dzn in $DATA
	do
		c=`expr $c + 1`
		dfilen=`basename $dzn`
		dznnoext=`echo $dfilen |cut -d'.' -f1`
		mzn2fzn $mzn -d $dzn -o $OUT/${mznnoext}/${mznnoext}_${dznnoext}.fzn
		echo ".\c"
	done
	
	if [ $c -eq 0 ]
	then
		mzn2fzn $mzn -o $OUT/${mznnoext}/${mznnoext}.fzn
		echo ".\c"
	fi 
	echo "done!"
done