name: Benchmarking
on:
  issue_comment:
    types: [ created ]
jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/bench'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'Execution of the performance test suite'
        if: steps.check.outputs.triggered == 'true'

  evaluate:
    needs: trigger
    runs-on: ubuntu-latest
    if: needs.trigger.outputs.triggered == 'true'
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: chocoteam/benchmarks
          path: ${{ github.workspace }}/parsers/src/test/resources/benchmarks
      # Regression tests
      - name: Test ${{ matrix.group }}
        run: mvn -B --file pom.xml test -DtestFailureIgnore=true -Dgroups="benchmark"
      - name: 'Upload perf results'
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/parsers/target/benchmark_results.csv